ConectSong/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
    path('', include('usuarios.urls')),
    path('', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat/urls.py
from django.urls import path
from .views import carregar_mensagens, enviar_mensagem

urlpatterns = [
    path('carregar-mensagens/<int:user_id>/', carregar_mensagens, name='carregar_mensagens'),
    path('enviar-mensagem', enviar_mensagem, name='enviar_mensagem'),
    # ... outras URLs do seu aplicativo ...
]

paginas/urls.py
from django.urls import path
from .views import IndexView, excluir_post

urlpatterns = [
    path('inicio', IndexView.as_view(), name='inicio'), 
    path('excluir/post', excluir_post, name='excluir-post'),
]

chat/models.py
from django.db import models

# Create your models here.

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User


sexo_opcoes = (('M', 'Masculino'), ('F', 'Feminino'), ('P', 'Prefiro não dizer'))

# Create your models here.
class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    foto_perfil = models.ImageField(upload_to='profile_images/', null=True, blank=True)
    foto_capa = models.ImageField(upload_to='cover_images/', null=True, blank=True)
    nome_completo = models.CharField(max_length=100, null=True, blank=True)
    atribuicao = models.CharField(max_length=255, null=True, blank=True)
    descricao = models.TextField(blank=True)
    data_nascimento = models.DateField(null=True, blank=True)
    sexo = models.CharField(max_length=1, choices=sexo_opcoes, null=True, blank=True) 
    cidade = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return f'{self.nome_completo}'

    def get_atribuicao_display(self):
        return self.atribuicao.split('/') if self.atribuicao else []
    

class Conexao(models.Model):
    enviou_solicitacao = models.ForeignKey(User, on_delete=models.CASCADE, related_name='conexao_enviada')
    recebeu_solicitacao = models.ForeignKey(User, on_delete=models.CASCADE, related_name='conexao_recebida')
    status = models.BooleanField(default=False)


class Post(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField(null=True, blank=True)
    data_publicacao = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-data_publicacao']


class Imagem(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    imagem = models.ImageField(upload_to='post_images/')


class Video(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    video = models.FileField(upload_to='post_videos/')


class Mensagem(models.Model):
    enviou = models.ForeignKey(User, on_delete=models.CASCADE, related_name='enviou')
    recebeu = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recebeu')
    mensagem = models.TextField()
    data_hora = models.DateTimeField(auto_now_add=True)

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from usuarios.models import Perfil, Post, sexo_opcoes

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(widget=forms.TextInput)
    error_messages = {
        'invalid_login': 'Email ou senha inválidos!',
    }


class PerfilForm(forms.ModelForm):
    atribuicao_opcoes = (('Cantor', 'Cantor'), ('Compositor', 'Compositor'), ('Produtor', 'Produtor'))

    atribuicao = forms.MultipleChoiceField(
        choices=(atribuicao_opcoes),  # Substitua com suas opções
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'atribuicao-checkbox'}),
    )
    sexo = forms.ChoiceField(choices=(sexo_opcoes), initial=None)

    class Meta:
        model = Perfil
        fields = ['nome_completo', 'foto_perfil', 'atribuicao', 'descricao', 'data_nascimento', 'cidade', 'sexo']
        widgets = {
            'foto_perfil' :forms.ClearableFileInput(attrs={'class': 'foto'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['atribuicao'].choices = self.atribuicao_opcoes

        atribuicao_atual = self.instance.atribuicao.split('/') if self.instance.atribuicao else []
        self.fields['atribuicao'].initial = atribuicao_atual


class PublicacaoForm(forms.ModelForm):
    texto = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'placeholder': 'Digite seu texto aqui...'}), required=False)
    imagem = forms.ImageField(required=False)
    video = forms.FileField(required=False)

    class Meta:
        model = Post
        fields = ['texto', 'imagem', 'video']

    '''def save(self, commit=True):
        if not (self.cleaned_data['texto'] or self.cleaned_data['imagem'] or self.cleaned_data['video']):
            return super().save(commit=False)  # Retorna a instância sem salvar no banco de dados
        return super().save(commit)'''

chat/views.py
import json
from django.shortcuts import get_object_or_404, render
from django.http import JsonResponse
from usuarios.models import Mensagem
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.views.decorators.http import require_POST
from django.contrib.auth.models import User


@login_required
def carregar_mensagens(request, user_id):
    
    mensagens = Mensagem.objects.filter(
        (Q(enviou=request.user, recebeu=user_id) | Q(enviou=user_id, recebeu=request.user))
    ).order_by('data_hora')

    mensagens_data = []
    for mensagem in mensagens:
        mensagem_data = {
            'message': mensagem.mensagem,
            'enviou_id': mensagem.enviou.id,
            'recebeu_id': mensagem.recebeu.id,
            'enviou_nome': mensagem.enviou.perfil.nome_completo,
            'recebeu_nome': mensagem.recebeu.perfil.nome_completo,
            'enviou_foto': str(mensagem.enviou.perfil.foto_perfil.url) if mensagem.enviou.perfil.foto_perfil else None,
            'recebeu_foto': str(mensagem.recebeu.perfil.foto_perfil.url) if mensagem.recebeu.perfil.foto_perfil else None,
            'data': mensagem.data_hora.strftime("%Y-%m-%d"),
            'hora': mensagem.data_hora.strftime("%H:%M"),
        }
        mensagens_data.append(mensagem_data)

    return JsonResponse({'mensagens': mensagens_data})


@login_required
def enviar_mensagem(request):
    try:
        # Obtenha os dados do corpo da requisição
        data = json.loads(request.body.decode('utf-8'))

        # Extraia os dados necessários
        mensagem = data.get('message')
        recebeu_id = data.get('receive')
        recebeu = get_object_or_404(User, id=recebeu_id)

        # Crie uma nova instância de Mensagem e salve-a no banco de dados
        nova_mensagem = Mensagem.objects.create(
            enviou=request.user,
            recebeu=recebeu,
            mensagem=mensagem
        )

        nova_mensagem.save()

        # Retorne uma resposta de sucesso
        return JsonResponse({'status': 'success'})

    except Exception as e:
        # Em caso de erro, retorne uma resposta de erro com uma mensagem apropriada
        return JsonResponse({'status': 'error', 'message': str(e)})

paginas/views.py
from typing import Any
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from usuarios.models import Post, Imagem, Video
from usuarios.views import voltar_para_pagina_anterior

# Create your views here.
class IndexView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('login')
    template_name = 'paginas/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all()
        return context
    

@login_required
def excluir_post(request):
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post = get_object_or_404(Post, id=post_id)

        if request.user == post.usuario:
            post.delete()

    return voltar_para_pagina_anterior(request)


@receiver(pre_delete, sender=Post)
def deletar_videos_e_fotos_relacionados(sender, instance, **kwargs):
    imagens_relacionadas = Imagem.objects.filter(post=instance)
    for imagem in imagens_relacionadas:
        imagem.imagem.delete()
        imagem.delete()

    videos_relacionados = Video.objects.filter(post=instance)
    for video in videos_relacionados:
        video.video.delete()
        video.delete()
    

paginas/templates/paginas/chat.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ConnectSong</title>

    <link rel="stylesheet" href="{% static 'css/chat.css' %}">
</head>
<body>

    <div id="chat-box">
        <div id="chat-head">
            <div id="chat-head-box">
                {% if perfil.foto_perfil %}
                    <img class="perfil-foto" src="/media/{{perfil.foto_perfil}}" alt="">
                {% else %}
                    <img class="perfil-foto" src="{% static 'img/perfil-generico.png' %}" alt="">
                {% endif %}
                <span>{{perfil.nome_completo}}</span>
                <button type="button" id="chat-close">
                    <i class="fa-solid fa-xmark"></i>
                </button>
            </div>
        </div>
        <div id="chat-body">
            <ul class="messages-container">
                <li class="messages received-by-me">
                    {% if perfil.foto_perfil %}
                        <img class="photo-user" src="/media/{{perfil.foto_perfil}}" alt="">
                    {% else %}
                        <img class="photo-user" src="{% static 'img/perfil-generico.png' %}" alt="">
                    {% endif %}
                    <div class="message-time-box">
                        <div class="message-ballon">
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe commodi eaque ab minus perferendis numquam, error iure alias, tempora deleniti id vel harum quasi impedit ex, soluta incidunt eum!
                        </div>
                        <div class="date-time-box">
                            <span class="date-message">15/09/2023</span>
                            <span class="time-message">17:12</span>
                        </div>
                    </div>
                </li>
                <li class="messages sent-by-me">
                    <div class="message-time-box">
                        <div class="message-ballon">
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe commodi eaque ab minus perferendis numquam, error iure alias, tempora deleniti id vel harum quasi impedit ex, soluta incidunt eum!
                        </div>
                        <div class="date-time-box">
                            <span class="date-message">15/09/2023</span>
                            <span class="time-message">17:12</span>
                        </div>
                    </div>
                </li>
                <li class="messages received-by-me">
                    {% if perfil.foto_perfil %}
                        <img class="photo-user" src="/media/{{perfil.foto_perfil}}" alt="">
                    {% else %}
                        <img class="photo-user" src="{% static 'img/perfil-generico.png' %}" alt="">
                    {% endif %}
                    <div class="message-time-box">
                        <div class="message-ballon">
                            Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        </div>
                        <div class="date-time-box">
                            <span class="date-message">25/10/2023</span>
                            <span class="time-message">09:37</span>
                        </div>
                    </div>
                </li>
                <li class="messages sent-by-me">
                    <div class="message-time-box">
                        <div class="message-ballon">
                            Lorem ipsum dolor sit amet.
                        </div>
                        <div class="date-time-box">
                            <span class="date-message">25/10/2023</span>
                            <span class="time-message">09:42</span>
                        </div>
                    </div>
                </li>
                <li class="messages sent-by-me">
                    <div class="message-time-box">
                        <div class="message-ballon">
                            Adipisicing elit
                        </div>
                        <div class="date-time-box">
                            <span class="date-message">25/10/2023</span>
                            <span class="time-message">09:42</span>
                        </div>
                    </div>
                </li>
                <li class="messages received-by-me">
                    {% if perfil.foto_perfil %}
                        <img class="photo-user" src="/media/{{perfil.foto_perfil}}" alt="">
                    {% else %}
                        <img class="photo-user" src="{% static 'img/perfil-generico.png' %}" alt="">
                    {% endif %}
                    <div class="message-time-box">
                        <div class="message-ballon">
                            Animi facere sit fugiat aperiam qui voluptatum laudantium in.
                        </div>
                        <div class="date-time-box">
                            <span class="date-message">25/10/2023</span>
                            <span class="time-message">09:44</span>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div id="chat-footer">
            <form id="form-message">
                {% csrf_token %}
                <div id="text-message-container">
                    <div id="text-message-box">
                        <label for="message-field" id="message-label">Escreva aqui sua mensagem</label>
                        <textarea autocomplete="off" name="message" id="message-field"></textarea>
                        <button type="button" class="btn-chat" id="btn-face-smile">
                            <i class="fa-solid fa-face-smile"></i>
                        </button>
                    </div>
                    <input type="hidden" name="receive" value="{{ perfil.usuario.id }}" id="receive">
                    <div>
                        
                    </div>
                    <button type="button" class="btn-chat" id="btn-send">
                        <?xml version="1.0" ?><svg class="send-icon" style="enable-background:new 0 0 24 24;" version="1.1" viewBox="0 0 24 24" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="info"/><g id="icons"><path d="M21.5,11.1l-17.9-9C2.7,1.7,1.7,2.5,2.1,3.4l2.5,6.7L16,12L4.6,13.9l-2.5,6.7c-0.3,0.9,0.6,1.7,1.5,1.2l17.9-9   C22.2,12.5,22.2,11.5,21.5,11.1z" id="send"/></g></svg>
                    </button>
                </div>
                <!-- <button class="btn-chat" id="btn-plus">
                    <div id="plus-box">
                        <i class="fa-solid fa-plus"></i>
                    </div>
                </button> -->
                <!-- <div id="chat-btn-box">
                    <label class="btn-chat">
                        <i class="fa-regular fa-image"></i>
                    </label>
                    <label class="btn-chat">
                        <i class="fa-solid fa-paperclip"></i>
                    </label>
                </div> -->
            </form>
        </div>
    </div>
</body>
</html>

paginas/templates/paginas/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ConnectSong</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/variaveis.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    <link rel="stylesheet" href="{% static 'css/btns.css' %}">

    {% block styles %}
        
    {% endblock %}
</head>
<body>

{% block head %}
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid" id="header-container">
                <div id="logo">
                    <img src="{% static 'img/ConnectSong.png' %}" alt=""> <h2 id="logo-text">Connect Song</h2>
                </div>
                <ul id="menu">
                    {% if request.user.is_authenticated %}
                    <li id="search-bar">
                        <form action="" id="search-form" method="GET">
                           <i class="fa fa-search"></i> <input type="search" placeholder="Pesquisar..." name="search" id="profile-search">
                        </form>
                        <ul id="profile-list"></ul>
                    </li>
                    <li class="menu-options" id="show-chats">
                        <i class="fa-regular fa-comment"></i>
                    </li>
                    <li class="menu-options" id="notifications">
                        <i class="fa-regular fa-bell"></i>
                    </li>
                    <li class="menu-options" id="fotoperfil-box">
                        <div id="open-lateral-menu">
                            {% if request.user.perfil.foto_perfil %}
                                <img class="perfil-foto" src="/media/{{request.user.perfil.foto_perfil}}" alt="">
                            {% else %}
                                <img class="perfil-foto" src="{% static 'img/perfil-generico.png' %}" alt="">
                            {% endif %}
                            <div id="lateral-menu-icon"><i class="fa-solid fa-bars"></i></div>
                        </div>
                        <ul id="lateral-menu"> 
                            <li id="perfil-box">
                                <a href="{% if request.user.perfil.usuario and request.user.username %}{% url 'ver-perfil' request.user.username %}{% endif %}">
                                    {% if request.user.perfil.foto_perfil %}
                                        <img class="perfil-foto" src="/media/{{request.user.perfil.foto_perfil}}" alt="">
                                    {% else %}
                                        <img class="perfil-foto" src="{% static 'img/perfil-generico.png' %}" alt="">
                                    {% endif %}
                                    <span>{{request.user.perfil.nome_completo}}</span>
                                </a>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'inicio' %}">
                                    <i class="fa-solid fa-house"></i>
                                    Página Inicial
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa-solid fa-gear"></i>
                                    Configurações
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa-solid fa-question"></i>
                                    Ajuda
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'logout' %}">
                                    <i class="fa-solid fa-right-from-bracket"></i>
                                    Sair
                                </a>
                            </li>
                        </ul>
                    </li>
                    {% else %}
                        <li id="login-option"><a href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
{% endblock %}

<main>
    {% block main %}
    <div class="container-fluid" id="main-container">
        {% block content %}
            <div id="container-posts">
                {% include 'paginas/publicar.html' %}
                {% include 'paginas/publicacoes.html' %}
            </div>
        {% endblock %}
    </div>
    {% endblock %}

    {% block chat %}
        {% include 'paginas/chat.html' %}
    {% endblock %}
</main>

{% block footer %}
<footer>
    <div class="col-12" id="copyright">
        <p>&copy; 2023 Copyright ConnectSong</p>
    </div>
</footer>
{% endblock %}

<script>
    var usuario_atual = '{{ request.user.id }}';
</script>

<!-- Scripts -->
<script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/fontawesome.js' %}"></script>
<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script src="{% static 'js/scripts.js' %}"></script>
<script src="{% static 'js/chat.js' %}"></script>

{% block scripts %}
    <script src="{% static 'js/inicio.js' %}"></script>
{%endblock %}
</body>
</html>

paginas/templates/paginas/publicacoes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ConnectSong</title>

    <link rel="stylesheet" href="{% static 'css/publicacoes.css' %}">
</head>
<body>
    <div id="publicacoes">
        {% for post in posts %}
            <div class="publicacao">
                <div class="post-header">
                    <div class="poster-user">
                        <a href="{% url 'ver-perfil' post.usuario.username %}">
                            {% if post.usuario.perfil.foto_perfil %}
                                <img class="perfil-foto" src="/media/{{post.usuario.perfil.foto_perfil}}" alt="">
                            {% else %}
                                <img class="perfil-foto" src="{% static 'img/perfil-generico.png' %}" alt="">
                            {% endif %}
                        </a> 
                        <div class="poster-user-box">
                            <a href="{% url 'ver-perfil' post.usuario.username %}" class="poster-name">{{post.usuario.perfil.nome_completo}}</a>
                            {% now "Y-m-d" as current_date %}
                            {% now "Y" as current_year %}

                            {% if post.data_publicacao|date:"Y-m-d" == current_date %}
                                <span class="post-date">Hoje às {{ post.data_publicacao|date:"H:i" }}</span>
                            {% else %}
                                {% if post.data_publicacao|date:"Y" == current_year %}
                                    <span class="post-date">{{ post.data_publicacao|date:"j" }} de {{ post.data_publicacao|date:"F" }}</span>
                                {% else %}
                                    <span class="post-date">{{ post.data_publicacao|date }}</span>
                                    {% endif %}
                            {% endif %}
                        </div>
                    </div>
                    {% if post.usuario == request.user %}
                        <div class="options-post">
                            <div class="btn-ellipsis" data-post-id="{{ post.id }}">
                                <div class="dot"></div>
                                <div class="dot"></div>
                                <div class="dot"></div>
                            </div>
                            <ul class="options-post-list" id="options_post_{{ post.id }}">
                                <li>
                                    <form method="post" action="{% url 'excluir-post' %}">
                                        {% csrf_token %}
                                            <input type="hidden" name="post_id" value="{{ post.id }}">
                                        <button type="submit" class="btn-post-options">
                                            <i class="fa-regular fa-trash-can"></i>
                                            Excluir Publicação
                                        </button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    {% endif %}
                </div>
                <div class="post-content">
                    {% if post.texto %}
                        <div class="text-post">
                            {{post.texto}}
                        </div>
                    {% endif %}
                    {% if post.imagem_set.exists or post.video_set.exists %}
                        {% for imagem in post.imagem_set.all %}
                            <div class="post-files" {% if post.texto %} style="padding-top: 5px;" {% endif %}>
                                <img src="/media/{{ imagem.imagem }}" alt="Imagem do post">
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="post-interaction">
                    <button class="btn-post-options">
                        <i class="fa-regular fa-thumbs-up"></i> <span>Curtir</span>
                    </button>
                    <button class="btn-post-options">
                        <i class="fa-solid fa-share"></i> <span>Compartilhar</span>
                    </button>
                </div>
            </div>
        {% endfor %}
    </div>
</body>
</html>

paginas/templates/paginas/publicar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ConnectSong</title>

    <link rel="stylesheet" href="{% static 'css/publicacoes.css' %}">
</head>
<body>
    <div id="publicacoes">
        <div id="publish post">
            <form action="{% url 'criar-publicacao' %}"  method="POST" enctype="multipart/form-data"  class="post-form" id="publicacao-form">
                {% csrf_token %}
                <div id="tela-publicacao">
                    <div id="poster">
                        <a href="{% if request.user.perfil.usuario and request.user.username %}{% url 'ver-perfil' request.user.username %}{% endif %}">
                            {% if request.user.perfil.foto_perfil %}
                                <img class="perfil-foto" src="/media/{{request.user.perfil.foto_perfil}}" alt="">
                            {% else %}
                                <img class="perfil-foto" src="{% static 'img/perfil-generico.png' %}" alt="">
                            {% endif %}
                        </a>
                        <div class="label-box" id="labels-publicacao">
                            <label for="id_imagem">
                                <i class="fa-solid fa-image"></i>
                                <span>Foto</span>
                                <input type="file" accept="image/jpeg, image/jpg, image/png" class="file" name="imagem" id="id_imagem">
                            </label>
                            <label for="id_video">
                                <i class="fa-solid fa-video"></i> <span>Vídeo</span>
                                <input type="file" accept="video/*" name="video" class="file" id="id_video">
                            </label>
                            <label for="id_texto">
                                <i class="fa-solid fa-align-left"></i>
                                <span>Aa</span>
                            </label>
                        </div>
                    </div>
                    <button class="btn btn-default" type="submit" id="btn-publicar">Publicar</button>
                </div>
                <textarea name="texto" id="id_texto" placeholder="Escreva sua publicação aqui..."></textarea>
                <div id="fotos-videos-box">
                    <img src="" alt="" id="inserir-imagem">
                </div>
            </form>
        </div>
    </div>
</body>
</html>