ConectSong/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
    path('', include('usuarios.urls')),
    path('', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat/urls.py
from django.urls import path
from .views import carregar_mensagens, enviar_mensagem

urlpatterns = [
    path('carregar-mensagens/<int:user_id>/', carregar_mensagens, name='carregar_mensagens'),
    path('enviar-mensagem', enviar_mensagem, name='enviar_mensagem'),
    # ... outras URLs do seu aplicativo ...
]

usuarios/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from usuarios.views import CustomLoginView, PerfilUpdate, PerfisResultados, VerPerfil, aceitar_conexao, alterar_foto_capa, alterar_foto_perfil, cancelar_solicitacao, criar_publicacao, pesquisar_perfis, solicitar_conexao
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='usuarios/login.html'
    ), name='logout'),
    path('perfil/editar', PerfilUpdate.as_view(), name='editar-perfil'),
    path('perfil/<str:username>', VerPerfil.as_view(), name='ver-perfil'),
    path('perfil/editar/capa', alterar_foto_capa, name='editar-capa'),
    path('perfil/editar/foto-perfil', alterar_foto_perfil, name='editar-foto-perfil'),
    path('pesquisar/perfis/', pesquisar_perfis, name='pesquisar-perfis'),
    path('perfis/resultados', PerfisResultados.as_view(), name='perfis-resultados'),

    path('solicitar/conexao', solicitar_conexao, name='enviar-solicitacao'),
    path('solicitacao/conexao/aceitar', aceitar_conexao, name='aceitar-solicitacao'),
    path('cancelar-solicitacao/', cancelar_solicitacao, name='cancelar-solicitacao'),
    path('criar/publicacao/', criar_publicacao, name='criar-publicacao'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User


sexo_opcoes = (('M', 'Masculino'), ('F', 'Feminino'), ('P', 'Prefiro não dizer'))

# Create your models here.
class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    foto_perfil = models.ImageField(upload_to='profile_images/', null=True, blank=True)
    foto_capa = models.ImageField(upload_to='cover_images/', null=True, blank=True)
    nome_completo = models.CharField(max_length=100, null=True, blank=True)
    atribuicao = models.CharField(max_length=255, null=True, blank=True)
    descricao = models.TextField(blank=True)
    data_nascimento = models.DateField(null=True, blank=True)
    sexo = models.CharField(max_length=1, choices=sexo_opcoes, null=True, blank=True) 
    cidade = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return f'{self.nome_completo}'

    def get_atribuicao_display(self):
        return self.atribuicao.split('/') if self.atribuicao else []
    

class Conexao(models.Model):
    enviou_solicitacao = models.ForeignKey(User, on_delete=models.CASCADE, related_name='conexao_enviada')
    recebeu_solicitacao = models.ForeignKey(User, on_delete=models.CASCADE, related_name='conexao_recebida')
    status = models.BooleanField(default=False)


class Post(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField(null=True, blank=True)
    data_publicacao = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-data_publicacao']


class Imagem(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    imagem = models.ImageField(upload_to='post_images/')


class Video(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    video = models.FileField(upload_to='post_videos/')


class Mensagem(models.Model):
    enviou = models.ForeignKey(User, on_delete=models.CASCADE, related_name='enviou')
    recebeu = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recebeu')
    mensagem = models.TextField()
    data_hora = models.DateTimeField(auto_now_add=True)

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from usuarios.models import Perfil, Post, sexo_opcoes

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(widget=forms.TextInput)
    error_messages = {
        'invalid_login': 'Email ou senha inválidos!',
    }


class PerfilForm(forms.ModelForm):
    atribuicao_opcoes = (('Cantor', 'Cantor'), ('Compositor', 'Compositor'), ('Produtor', 'Produtor'))

    atribuicao = forms.MultipleChoiceField(
        choices=(atribuicao_opcoes),  # Substitua com suas opções
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'atribuicao-checkbox'}),
    )
    sexo = forms.ChoiceField(choices=(sexo_opcoes), initial=None)

    class Meta:
        model = Perfil
        fields = ['nome_completo', 'foto_perfil', 'atribuicao', 'descricao', 'data_nascimento', 'cidade', 'sexo']
        widgets = {
            'foto_perfil' :forms.ClearableFileInput(attrs={'class': 'foto'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['atribuicao'].choices = self.atribuicao_opcoes

        atribuicao_atual = self.instance.atribuicao.split('/') if self.instance.atribuicao else []
        self.fields['atribuicao'].initial = atribuicao_atual


class PublicacaoForm(forms.ModelForm):
    texto = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'placeholder': 'Digite seu texto aqui...'}), required=False)
    imagem = forms.ImageField(required=False)
    video = forms.FileField(required=False)

    class Meta:
        model = Post
        fields = ['texto', 'imagem', 'video']

    '''def save(self, commit=True):
        if not (self.cleaned_data['texto'] or self.cleaned_data['imagem'] or self.cleaned_data['video']):
            return super().save(commit=False)  # Retorna a instância sem salvar no banco de dados
        return super().save(commit)'''

usuarios/views.py
from django.conf import settings
from django.db.models import  Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from usuarios.models import Perfil, Conexao, Post, Imagem, Video
from django.views.generic import TemplateView
from .forms import CustomAuthenticationForm, PerfilForm
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .forms import PublicacaoForm


class CustomLoginView(LoginView):
    template_name = 'usuarios/login.html'
    authentication_form = CustomAuthenticationForm

class VerPerfil(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('login')
    template_name = 'usuarios/perfil.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        username = self.kwargs.get('username')
        user = get_object_or_404(User, username=username)
        perfil = Perfil.objects.get(usuario=user.id) 

        conexao = Conexao.objects.filter(
            (Q(enviou_solicitacao=self.request.user) & Q(recebeu_solicitacao=perfil.usuario)) |
            (Q(enviou_solicitacao=perfil.usuario) & Q(recebeu_solicitacao=self.request.user))
        ).first()

        conexoes = Conexao.objects.filter((Q(enviou_solicitacao=perfil.usuario) | Q(recebeu_solicitacao=perfil.usuario)) & Q(status=True))[:6]

        connections = []

        for connect in conexoes: 
            if connect.enviou_solicitacao != perfil.usuario:
                connection = connect.enviou_solicitacao
            else:
                connection = connect.recebeu_solicitacao

            connections.append(connection.perfil)

        context['perfil'] = perfil
        context['conexao'] = conexao
        context['posts'] = Post.objects.filter(usuario=user)
        context['connections'] = connections
        context['qtd_connections'] = conexoes.count()
        
        return context
    

class PerfilUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    template_name = 'usuarios/form_perfil.html'
    model = Perfil
    form_class = PerfilForm

    def get_object(self, queryset=None):
        if self.request.user.is_authenticated:
            return self.request.user.perfil
        return None

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['atribuicao'].initial = [opcao[0:] for opcao in form.instance.get_atribuicao_display()]
        return form

    def form_valid(self, form):
        atribuicao_selecionada = [item[0:] for item in form.cleaned_data['atribuicao']]
        sexo = form.cleaned_data['sexo']
        atribuicao_ajustada = atribuicao_selecionada

        if sexo == 'F':
            atribuicao_ajustada = [opcao + 'a' for opcao in atribuicao_selecionada]
        elif sexo == 'P' or sexo == '':
            atribuicao_ajustada = [opcao + '(a)' for opcao in atribuicao_selecionada]
        
        form.instance.atribuicao = '/'.join(atribuicao_ajustada)
        return super().form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        user = self.request.user
        perfil = Perfil.objects.get(usuario=user)

        foto = {
            'foto': perfil.foto_perfil if perfil.foto_perfil else '',
        }
        context['foto'] = foto

        return context

    def get_success_url(self):
        username = self.request.user.username
        success_url = reverse('ver-perfil', kwargs={'username': username})
        return success_url
        

@login_required
def criar_publicacao(request):
    if request.method == 'POST':
        form = PublicacaoForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.usuario = request.user  
            post.save()

            imagem = form.cleaned_data.get('imagem')
            if imagem:
                Imagem.objects.create(post=post, imagem=imagem)

            video = form.cleaned_data.get('video')
            if video:
                Video.objects.create(post=post, video=video)

            # Redirecionar de volta para a página anterior
            return redirect(request.META.get('HTTP_REFERER', 'inicio'))
    else:
        form = PublicacaoForm()

    return render(request, 'paginas/index.html', {'form': form})


'''def editar_publicacao(request):
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post = get_object_or_404(Post, id=post_id)

        form = PublicacaoForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.usuario = request.user  
            post.save()

            imagem = form.cleaned_data.get('imagem')
            if imagem:
                Imagem.objects.create(post=post, imagem=imagem)

            video = form.cleaned_data.get('video')
            if video:
                Video.objects.create(post=post, video=video)

            # Redirecionar de volta para a página anterior
            return redirect(request.META.get('HTTP_REFERER', 'inicio'))

    return render(request, 'paginas/index.html', {'form': form, 'post': post})'''


@login_required
def alterar_foto_capa(request):
    if request.method == 'POST':
        id_perfil = request.POST.get('id-perfil')
        nova_foto_capa = request.FILES.get('foto-capa')
        perfil = get_object_or_404(Perfil, pk=id_perfil)

        if nova_foto_capa:
            perfil.foto_capa = nova_foto_capa
            perfil.save()
    return voltar_para_pagina_anterior(request)


def alterar_foto_perfil(request):
    if request.method == 'POST':
        id_perfil = request.POST.get('id-perfil')
        nova_foto_perfil = request.FILES.get('foto-perfil')
        perfil = get_object_or_404(Perfil, pk=id_perfil)

        if nova_foto_perfil:
            perfil.foto_perfil = nova_foto_perfil
            perfil.save()
    return voltar_para_pagina_anterior(request) 


class PerfisResultados(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Perfil
    template_name = 'usuarios/lista/resultados_pesquisa.html'

    def get_queryset(self):

        caracteres = self.request.GET.get('search')

        perfis = Perfil.objects.filter(
            Q(nome_completo__istartswith=caracteres) |
            Q(nome_completo__icontains=f' {caracteres}')
        ).order_by('-nome_completo')

        user_in_list = any(perfil.usuario == self.request.user for perfil in perfis)

        if user_in_list:
            perfis = sorted(perfis, key=lambda p: p.usuario != self.request.user, reverse=True)


        conexoes = Conexao.objects.filter(Q(enviou_solicitacao=self.request.user) | Q(recebeu_solicitacao=self.request.user))

        for perfil in perfis:
            perfil.conexao = self.get_connection(conexoes, perfil)

        return perfis

    def get_connection(self, conexoes, perfil):
        for conexao in conexoes:
            if conexao.enviou_solicitacao == perfil.usuario or conexao.recebeu_solicitacao == perfil.usuario:
                return conexao
        return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['conexoes'] = self.get_connections(self.object_list)
        return context

    def get_connections(self, perfis):
        return [perfil.conexao for perfil in perfis]


@login_required
def pesquisar_perfis(request): 
    if request.method == 'GET':
        caracteres = request.GET.get('search')

        perfis = Perfil.objects.filter(
            Q(nome_completo__istartswith=caracteres) |
            Q(nome_completo__icontains=f' {caracteres}')
        ).order_by('-nome_completo')[:8]


        perfis_lista = []
        for perfil in perfis:
            perfil_data = {
                'perfil_username': perfil.usuario.username,
                'nome_completo': perfil.nome_completo,
                'foto_perfil': perfil.foto_perfil.url if perfil.foto_perfil else None,
                'atribuicao': perfil.atribuicao
            }
            perfis_lista.append(perfil_data)

        return JsonResponse({'perfis': perfis_lista})
    else:
        return JsonResponse({'erro': 'Apenas métodos GET são permitidos'})


def voltar_para_pagina_anterior(request):
    url_anterior = request.META.get('HTTP_REFERER', reverse('inicio'))
    return redirect(url_anterior)


@login_required
def solicitar_conexao(request):
    recebeu_solicitacao = request.POST.get('recebeu-solicitacao')
    conectar_a_usuario = get_object_or_404(User, id=recebeu_solicitacao)

    if not Conexao.objects.filter(enviou_solicitacao=request.user, recebeu_solicitacao=conectar_a_usuario).exists():
        Conexao.objects.create(enviou_solicitacao=request.user, recebeu_solicitacao=conectar_a_usuario)

    return voltar_para_pagina_anterior(request)    


@login_required
def aceitar_conexao(request):
    if request.method == 'POST':
        conexao_id = request.POST.get('conexao-id')
        conexao = get_object_or_404(Conexao, id=conexao_id)

        if request.user == conexao.recebeu_solicitacao:
            conexao.status = True
            conexao.save()

    return voltar_para_pagina_anterior(request)
    

@login_required
def cancelar_solicitacao(request):
    if request.method == 'POST':
        conexao_id = request.POST.get('conexao_id')
        conexao = get_object_or_404(Conexao, id=conexao_id)

        if request.user == conexao.enviou_solicitacao:
            conexao.delete()

    return voltar_para_pagina_anterior(request)



'''@login_required

usuarios/templates/usuarios/form_perfil.html
{% extends 'paginas/index.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/form-perfil.css' %}">
{% endblock %}

{% block content %}

<div class="form-container">
    <form action="" method="POST" enctype="multipart/form-data" id="form-perfil">
        {% csrf_token %}
        <div id="foto_nome-box">
            <div class="input-field" id="input-foto">
                <label for="{{ form.foto_perfil.id_for_label }}" id="label-foto">
                    <!-- {% if foto %}
                        <img src="/media/{{foto.foto_perfil}}" alt="" id="imagem-perfil">
                    {% else %} 
                        <img src="{% static 'img/perfil-generico.png' %}" alt="" id="imagem-perfil">
                    {% endif %} -->
                    <img src="{% static 'img/perfil-generico.png' %}" alt="" id="imagem-perfil">
                    <div id="icone-box">
                        <i class="fa-solid fa-camera"></i>
                    </div>
                </label>
                <div class="file-field">
                    {{form.foto_perfil}}
                </div>
            </div>
            <div class="input-field" id="field-nome">
                {{form.nome_completo}}
                <label for="{{ form.nome_completo.id_for_label }}" id="label-nome" class="btn-default">
                    <i class="fa-solid fa-pencil"></i>
                </label>
            </div>
        </div>
        <div class="input-field" id="field-atribuicao">
            <label id="lbl-atribuicao">O que você é ? <span>(Selecione uma ou mais opções)</span></label>
            <div id="checkox-container">
                {% for checkbox_id, checkbox_label in form.fields.atribuicao.choices %}
                    <div class="checkbox">
                        <input type="checkbox" name="atribuicao" id="{{ checkbox_id }}" value="{{ checkbox_id }}"
                            {% if checkbox_id in form.initial.atribuicao %}checked{% endif %}>
                        <label class="label-select" for="{{ checkbox_id }}">
                            <i class="fa fa-check"></i> {{ checkbox_label }}(a)
                        </label>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="input-field">
            <label for="{{ form.descricao.id_for_label }}">Descrição</label>
            {{form.descricao}}
        </div>
        <div class="input-group">
            <div class="input-field">
                <label for="{{ form.data_nascimento.id_for_label }}">Nascimento</label>
                {{form.data_nascimento}}
            </div>
            <div class="input-field" id="input-cidade">
                <label for="{{ form.cidade.id_for_label }}">Cidade</label>
                {{form.cidade}}
            </div>
            <div class="input-field" id="field-sexo">
                <label for="{{ form.descricao.id_for_label }}">Sexo</label>
                {{form.sexo}}
            </div>
        </div>
        <div class="btn-box">
            <button type="submit" class="btn-default">Salvar Alterações</button>
        </div>
            <!-- {{ form|crispy }} -->
    </form>
</div>

{% endblock %}

{% block scripts %}

<script>
    $(document).ready(function() {
        $('#id_foto_perfil').on('change', function(e) {
            var input = e.target;
            if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                // Define a imagem de pré-visualização
                $('#imagem-perfil').attr('src', e.target.result);
            };

            // Carrega o arquivo de imagem
            reader.readAsDataURL(input.files[0]);
            }
        });

    });
</script>

<script>
    $(document).ready(function() {
        
        $('#label-nome').click(function() {
            const input = $('#id_nome_completo');
            var nome = input.val();
            input[0].setSelectionRange(nome.length, nome.length);
            input.focus();
        });
        
        var nome =$('#id_nome_completo').val();
        console.log(nome);

        $('#id_data_nascimento').mask('00/00/0000');
        var telefoneMask = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        }, 
        telOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(telefoneMask.apply({}, arguments), options);
            }
        };
        $('#id_telefone').mask(telefoneMask, telOptions);
        
        var foto = '{{foto.foto}}';
        if (foto) {
            $('#imagem-perfil').attr("src","/media/" + foto);
        } 
    });
</script>

<script>
    $(document).ready(function() {
        $('button').on('click', function() {
            var inputField = $('#id_atribuição');
            var button = $(this);

            var existingValues = inputField.val().split('/');

            var index = existingValues.indexOf(button.text());

            if (index === -1) {
                existingValues.push(button.text());
                button.addClass("selected");
            } else {
                existingValues.splice(index, 1);
                button.removeClass("selected");
            }

            inputField.val(existingValues.join('/'));
        });
    });
</script>

{%endblock %}

usuarios/templates/usuarios/login.html
{% extends 'paginas/index.html' %}

{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <style>
    
    </style>
{% endblock %}

{% block content %}

<div class="form-container">
                
    <div class="form-box"> 
        {% block titulo-form %}
            <h2 class="titulo-form">Conect Song</h2> <br>
        {% endblock%}

        <form id="form-login" action="" method="POST">
            {% csrf_token %}

            <div class="input-field">
                <label for="{{ form.username.id_for_label }}">Email</label>
                {{ form.username }}
            </div>

            <div class="input-field pasword-box">
                <label for="{{ form.password.id_for_label }}">Senha</label>
                {{ form.password }}
                {% if form.non_field_errors %}
                    <p class="error">{{ form.non_field_errors.as_text }}</p>
                {% endif %}
            </div>
            <div id="box-btn">
                <button type="submit" class="btn btn-login">Login</button>
                <a id="redefinir-senha" href="#">Esqueceu sua Senha?</a>
                <hr>
            </div>
        </form>
        <a class="btn btn-cadastrar" href="{% url 'cadastrar-usuario' %}">Cadastrar</a>
    </div>
</div>

{% endblock %}